### ISSUE TITLE
"Unexpected end of JSON input" -Win10 VS Code 1.54.1

### ISSUE THREAD

**Issue by emdashdrupal** [errata-ai/vale-vscode#50]
I had Vale working within VS Code and then it suddenly stopped. I'm not sure what/if anything changed.

The only error I see is "Unexpected end of JSON input"

Windows 10
vale version 2.9.1 (directly downloaded)
VS Code 1.54.1

.vale.ini
StylesPath = "h:/vale/styles"

[*.md]
BasedOnStyles = Vale,  <proprietary> (still doesn't work only with Vale selected)

**Comment by emdashdrupal** [comment]
I tested this on a separate VS Code install that never had Vale or the extension installed and can confirm similar results.

StylesPath = styles
# Vocab = Blog
[*]
BasedOnStyles = Vale, Microsoft

**Comment by jdkato** [comment]
I think this might be the same issue as #49.

**Comment by ChrisChinchilla** [comment]
Can you confirm if this is now fixed after upgrading to Vale 2.10.2 @emdashdrupal ?

**Comment by emdashdrupal** [comment]
> 
> 
> Can you confirm if this is now fixed after upgrading to Vale 2.10.2 @emdashdrupal ?

Unfortunately, no, it still persists.

**Comment by ChrisChinchilla** [comment]
@emdashdrupal I tested Vale 2.10.2 on a vanilla Windows installation, with the ini file from above (minus the style path) and it worked as expected. My only other thought is that you maybe have some styles in the style path that are malformed?

**Comment by kbatuigas** [comment]
Hi, I'm experiencing this issue as well. I'm using Windows 10, Vale 2.10.2, VS Code 1.55.2. I was initially trying this with my own project where I had no styles added and all I had in my .vale.ini was `BasedOnStyles = Vale`, but even with the [boilerplate repo](https://github.com/errata-ai/vale-boilerplate) I'm still getting `SyntaxError: Unexpected end of JSON input` from Vale output.

**Comment by jdkato** [comment]
Could you try running `vale ls-config` from the root directory on the command line? My guess is that the `StylesPath` doesn't exist.

**Comment by kbatuigas** [comment]
Hi, this is what I see:

```
PS C:\> vale ls-config
E100 [.vale.ini] Runtime error

open : The system cannot find the file specified.

Execution stopped with code 1.
{
  "BlockIgnores": {},
  "Checks": null,
  "Formats": {},
  "GBaseStyles": null,
  "GChecks": {},
  "IgnoredClasses": null,
  "IgnoredScopes": null,
  "MinAlertLevel": 1,
  "Project": "",
  "RuleToLevel": {},
  "SBaseStyles": {},
  "SChecks": {},
  "SkippedScopes": null,
  "Stylesheets": {},
  "StylesPath": "",
  "TokenIgnores": {},
  "WordTemplate": "",
  "DictionaryPath": ""
}
2021/05/03 09:05:35 E100 [.vale.ini] Runtime error

open : The system cannot find the file specified.

Execution stopped with code 1.
```

**Comment by jdkato** [comment]
This means that Vale can't find your `.vale.ini` file. Do you have one in a parent directory of the files you're editing?

**Comment by kbatuigas** [comment]
Yup, I do! There is one personal project where I've added `.vale.ini` to the project root, and I have the vale-boilerplate repo as well and I've left `.vale.ini` in the project root too.

**Comment by cbelsole** [comment]
I fixed this by copying the folder structure of the example repo.

`styles > Vocab > Blog`

That's what vale is expecting. The error could be better, but I don't think this is a bug.

**Comment by alexwine36** [comment]
I am having the same problem on Mac using Vale v2.20.1 and plugin version v0.15.2

Running vale ls-config returns 
{
  "BlockIgnores": {},
  "Checks": [
    "write-good.E-Prime",
    "Google.Headings",
    "Google.Acronyms",
    "Google.Latin",
    "Google.Exclamation",
    "Google.Units"
  ],
  "Formats": {
    "mdx": "md"
  },
  "Asciidoctor": {},
  "FormatToLang": {},
  "GBaseStyles": null,
  "GChecks": {},
  "IgnoredClasses": null,
  "IgnoredScopes": null,
  "MinAlertLevel": 0,
  "Vocab": [
    "Base"
  ],
  "RuleToLevel": {
    "Google.Exclamation": "warning",
    "Google.Units": "warning"
  },
  "SBaseStyles": {
    "*.{md,mdx}": [
      "Vale",
      "Google",
      "proselint",
      "write-good",
      "AlexStyle",
      "alex",
      "Joblint"
    ]
  },
  "SChecks": {
    "*.{md,mdx}": {
      "Google.Acronyms": false,
      "Google.Exclamation": true,
      "Google.Headings": false,
      "Google.Latin": false,
      "Google.Units": true,
      "write-good.E-Prime": false
    }
  },
  "SkippedScopes": null,
  "Stylesheets": {},
  "StylesPath": "/Users/alexanderwine/Documents/Programming.nosync/Node/NX/portfolio/.github/styles",
  "TokenIgnores": {},
  "WordTemplate": "",
  "DictionaryPath": "",
  "NLPEndpoint": ""
}

**Comment by phxnsharp** [comment]
Using GitHub Codespaces, Vale 2.20.2, Vale-VSCode 0.15.2. Vale works fine by itself from the command line with a variety of ways of calling it. The only message I get from the UI is "SyntaxError: Unexpected end of JSON input", not even a stack trace. I would really love to have this integration! Some type of way to turn up the logging to know what it is trying to do might help.

**Comment by phxnsharp** [comment]
In case someone else finds this useful, my problem was that it does not accept the '~' character in the path to vale in the plug-in settings (in case Vale is not installed to your path). Using the full path works.

This is a classic case of not reporting proper errors to the user. If the vale log window had said `command "~/vale/vale" not found`, I would have self-solved this in minutes instead of a day later.

**Comment by JulienMartens** [comment]
In case it helps someone : I installed Vale following [the official tutorial](https://vale.sh/docs/vale-cli/installation/) and ran into the same "Unexpected JSON input". 

After a lot of searching, I realised that the tutorial makes you install an older version of Vale(2.15.4)...getting the newest version from [here](https://github.com/errata-ai/vale/releases/) solved the issue !

Updating the vale.sh tutorial might be a good idea to prevent other people from falling in the same trap :smile:
